version: '3.8'
services:
  pagos:
    build:
      context: ../Pagos
    ports:
      - "8085:8080"
    volumes:
      - ./wallet:/app/wallet
    environment:
      - SPRING_APPLICATION_NAME=Pagos
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@basefullstack_high?TNS_ADMIN=/app/wallet
      - SPRING_DATASOURCE_USERNAME=USUARIO_FULLSTACK
      - SPRING_DATASOURCE_PASSWORD=RenatayGaspar$2019
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.OracleDialect
    networks:
      - backend

networks:
  backend:
    driver: bridge